---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cur8s/flux.git
  ref:
    branch: main
  sparseCheckout:
    - releases/2.7
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cur8s/flux.git
  ref:
    branch: main
  sparseCheckout:
    - src/2.7/test-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./releases/2.7
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 10m
  path: src/2.7/test-cluster
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux
